version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=rapid_cluster
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1014m -Xmx1014m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  fuseki:
    image: stain/jena-fuseki:latest
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pw123
  rapid:
    image: delvingbv/rapid:0.1.5
    container_name: rapid
    ports:
      - "3000:3000"
    depends_on: ['elasticsearch']
    environment:
      - "RAPID_ELASTICSEARCH_URLS=http://elasticsearch:9200"
      - "RAPID_HTTP_PORT=3000"

